#
#    
#    ██╗░░██╗░█████╗░██████╗░██╗░░░██╗███████╗░██████╗████████╗░░░░░░░
#    ██║░░██║██╔══██╗██╔══██╗██║░░░██║██╔════╝██╔════╝╚══██╔══╝░░██╗░░
#    ███████║███████║██████╔╝╚██╗░██╔╝█████╗░░╚█████╗░░░░██║░░░██████╗
#    ██╔══██║██╔══██║██╔══██╗░╚████╔╝░██╔══╝░░░╚═══██╗░░░██║░░░╚═██╔═╝
#    ██║░░██║██║░░██║██║░░██║░░╚██╔╝░░███████╗██████╔╝░░░██║░░░░░╚═╝░░
#    ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░░░░╚═╝░░░░░░░░░░
#
#                       Faster crops harvesting
#
#
# Main plugin working switcher
enabled: true